# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-05 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('date_shipped', models.DateTimeField()),
                ('date_arrived', models.DateTimeField(blank=True)),
            ],
        ),
    ]
